name: Fix image paths for email templates

on:
  push:
    paths:
      - '**.html'

jobs:
  fix-paths:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para que el bot pueda escribir en el repo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Replace paths
        run: |
          BASE_URL="https://luchogranadosg.github.io/testactions"
          find . -name "*.html" -not -path "./.git/*" | while read file; do
            sed -i 's|src="\(\.\./\)\+assets/images/|src="'"$BASE_URL"'/assets/images/|g' "$file"
            sed -i 's|src='"'"'\(\.\./\)\+assets/images/|src='"'"''"$BASE_URL"'/assets/images/|g' "$file"
          done

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: replace local image paths with GitHub Pages URLs"
          branch: main